default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>

development:
  <<: *default
  database: houston_development

test:
  <<: *default
  database: houston_test

production:
  <<: *default
  database: houston_production
  username: houston
  password: <%= ENV["HOUSTON_DATABASE_PASSWORD"] %>
